version: '3'

services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/src
    ports:
      - "8000:8000"

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  selenium-chrome:
    image: selenium/node-chrome
    environment:
      HUB_HOST: selenium-hub
    depends_on:
      - selenium-hub

  selenium-firefox:
    image: selenium/node-firefox
    environment:
      HUB_HOST: selenium-hub
    depends_on:
      - selenium-hub
